import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>National Aviary Escape Puzzle Hunt!</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					National Aviary Escape Puzzle Hunt!
				</h1>

				<p className={styles.description}>
					<a href="https://docs.google.com/document/d/1bI9MeZ_xE3iE0piS5RnAam-3uBucCKlI4jc16TNh0zc/edit?usp=sharing">Instructions</a>
				</p>

				<button><a href="/level-1">Continue</a></button>
			</main>
		</div>
	)
}

export default Home
